services:
  web:
    #image: reg.kevinsyk.es/sirbomble/cs350-project-1:latest
    build: .
    container_name: carbio-web
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["node", "/app/backend/dist/index.js"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:17"
    container_name: carbio-postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carbio -d thedatabase"]
      interval: 10s
      timeout: 5s
      retries: 5